

{
    'name': 'eduvault Library',
    'version': '18.0.1.0',
    'license': 'LGPL-3',
    'category': 'eduvault',
    "sequence": 3,
    'summary': 'Manage Library',
    'complexity': "easy",
    'author': 'eduvault Inc',
    'website': 'https://www.eduvault.org',
    'depends': [
        'account',
        'base_automation',
        'eduvault_activity',
        'eduvault_parent',
        'web',
        'base'
    ],
    'data': [
        'security/op_security.xml',
        'security/ir.model.access.csv',
        'data/custom_paperformat.xml',
        'data/media_queue_sequence.xml',
        'data/action_rule_data.xml',
        'data/product_demo.xml',
        'report/report_media_barcode.xml',
        'report/report_library_card_barcode.xml',
        'report/report_student_library_card.xml',
        'report/report_menu.xml',
        'wizards/issue_media_view.xml',
        'wizards/return_media_view.xml',
        'wizards/reserve_media_view.xml',
        'views/media_view.xml',
        'views/media_unit_view.xml',
        'views/media_movement_view.xml',
        'views/media_purchase_view.xml',
        'views/media_queue_view.xml',
        'views/library_view.xml',
        'views/author_view.xml',
        'views/publisher_view.xml',
        'views/tag_view.xml',
        'views/media_type_view.xml',
        'views/student_view.xml',
        'views/faculty_view.xml',
        'menus/op_menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
